### ISSUE TITLE
Initial Public Release 

### ISSUE THREAD

**Issue by migara** [PaloAltoNetworks/terraform-panos-ngfw-modules#16]
- [x] Change `panorama_mode` variable - The variable should be renamed to `panorama` to avoid any ambiguity #19
- [x] Bump the minimum required Terraform version to 1.4 #19
- [x] Support [destination_devices](https://github.com/PaloAltoNetworks/terraform-provider-panos/blob/4aac7586c49af3e1ffef11224d4a31616125e159/panos/security_rules.go#LL672C7-L672C26) attribute in the `policy` module #19
- [x] Add a [reverse lookup map] (https://registry.terraform.io/providers/PaloAltoNetworks/panos/latest/docs/resources/administrative_tag), so the user can define colours based on the actual colour name #19
- [x] Add `template_stack` attribute support to the `network` module #19
- [x] Remove `commit-push` module from the initial release and move it to a draft PR #19
- [x] Split `object` module into `addresses`, `services`, `tags` modules #19
- [x] Split `policy` module into `security_policies` and `nat_policies` #19
- [ ] Verify all the README files - There are some code snippets pointing to old Terraform module references 
- [x] Enhance type validation of the variables instead of using type(any)
- [x] Simplify the examples to use HCL and remove json, yaml and csv examples
- [x] #18
- [x] Add basic workflow using pre-commit like in rest of our repositories (potentially reuse https://github.com/PaloAltoNetworks/terraform-modules-vmseries-ci-workflows)
- [x] Add release workflow (0.1.0v)
